name: mapbox_gl_language_dart
description: mapbox-gl-language for Dart
version: 1.0.0
repository: https://github.com/noroshii-main/mapbox-gl-language-dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.3
  mapbox_gl_dart:
    git:
      url: https://github.com/noroshii-main/mapbox-gl-dart.git

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.0.0 <3.0.0"
