name: mapbox_gl_language_dart
description: mapbox-gl-language for Dart
version: 1.0.0
repository: https://github.com/noroshii-main/mapbox-gl-language-dart
publish_to: none

environment:
  sdk: ^3.3.2

dependencies:
  js: ^0.7.1
  mapbox_gl_dart:
    git: https://github.com/noroshii-main/mapbox-gl-dart

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
