name: mapbox_gl_language_dart
description: mapbox-gl-language for Dart
version: 1.0.0
repository: https://github.com/noroshii-main/mapbox-gl-language-dart
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  js: ">=0.6.0"
  mapbox_gl_dart:
    git:
      url: https://github.com/noroshii-main/mapbox-gl-dart.git

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
